---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Instala Apache
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ apache_packages }}"

- name: Instala módulos PHP
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ php_packages }}"

- name: Creando directorio para data moddle
  ansible.builtin.file:
    path: /var/www/moodledata
    state: directory
    owner: "{{ usuario_apache }}"
    group: "{{ grupo_apache }}"
    mode: 0755

- name: Descarga y descomprime moodle
  ansible.builtin.unarchive:
    src: "{{ moodle_url }}"
    dest: /var/www
    remote_src: true
    owner: "{{ usuario_apache }}"
    group: "{{ grupo_apache }}"

- name: Apache virtualhost
  ansible.builtin.template:
    src: "files/sitio.conf.j2"
    dest: "/etc/apache2/sites-available/{{ server_name }}.conf"

- name: Eliminando index.html
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

- name: Desactivando server_name por default
  ansible.builtin.command: a2dissite 000-default

- name: Creando carpeta para SSL
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/ssl/certs
    - /etc/ssl/private

- name: Genera Private key
  community.crypto.openssl_privatekey:
    path: /etc/ssl/private/{{ server_name }}.key

- name: Genera CSR
  community.crypto.openssl_csr:
    path: /etc/ssl/certs/{{ server_name }}.csr
    privatekey_path: /etc/ssl/private/{{ server_name }}.key
    common_name: "{{ server_name }}"
    country_name: AR
    email_address: "{{ email }}"
    organization_name: Home

- name: Genera Certificado auto-firmado
  community.crypto.x509_certificate:
    path: /etc/ssl/certs/{{ server_name }}.crt
    privatekey_path: /etc/ssl/private/{{ server_name }}.key
    csr_path: /etc/ssl/certs/{{ server_name }}.csr
    provider: selfsigned

- name: Activa Apache mods
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  with_items: "{{ apache_mods }}"
  notify: servicios_apache

- name: Activa sitio
  ansible.builtin.shell: /usr/sbin/a2ensite {{ server_name }}
  notify: servicios_apache