---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Creando directorio para moodle
  ansible.builtin.file:
    path: /var/www/moodle_src
    state: directory
    owner: "{{ usuario_apache }}"
    group: "{{ grupo_apache }}"
    mode: 0755

- name: Creando directorio para data moddle
  ansible.builtin.file:
    path: /var/www/moodle_src/moodledata
    state: directory
    owner: "{{ usuario_apache }}"
    group: "{{ grupo_apache }}"
    mode: 0777

- name: Descarga y descomprime moodle
  ansible.builtin.unarchive:
    src: "{{ moodle_url }}"
    dest: /var/www/moodle_src
    remote_src: true
    owner: "{{ usuario_apache }}"
    group: "{{ grupo_apache }}"

- name: Apache virtualhost
  ansible.builtin.template:
    src: "files/sitio.conf.j2"
    dest: "/etc/apache2/sites-available/{{ server_name }}.conf"

- name: Activar sitio
  ansible.builtin.shell: /usr/sbin/a2ensite {{ server_name }}
  notify: servicios_apache